name: ci_preview

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build and push Docker preview image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Oracle Cloud Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCIR_REGISTRY }}
          username: ${{ secrets.OCIR_USERNAME }}
          password: ${{ secrets.OCIR_AUTH_TOKEN }}
      # Docs: https://docs.oracle.com/pt-br/iaas/Content/Registry/Tasks/registrypushingimagesusingthedockercli.htms

      - name: Build Docker image
        with:
          context: .
          file: Dockerfile
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t "${{ secrets.OCIR_REGISTRY }}/${{ secrets.OCI_TENACY_NAMESPACE }}/${{ secrets.OCIR_REPO_NAME }}:preview" .

      - name: Push Docker image
        run: docker push "${{ secrets.OCIR_REGISTRY }}/${{ secrets.OCI_TENACY_NAMESPACE }}/${{ secrets.OCIR_REPO_NAME }}:preview"
