name: CI_Develop

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build and publish Docker preview image
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Oracle Cloud Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.OCIR_REGISTRY }}
          username: ${{ secrets.OCIR_USERNAME }}
          password: ${{ secrets.OCIR_AUTH_TOKEN }}
      # Docs: https://docs.oracle.com/pt-br/iaas/Content/Registry/Tasks/registrypushingimagesusingthedockercli.htms
      - name: Build Docker Image
        run: |
          echo "Building the Docker image..." /
          docker build . /
          --platform linux/arm64 /
          --build-arg ALGOLIA_ADMIN_API_KEY="${{ secrets.ALGOLIA_ADMIN_API_KEY }}" \
          --build-arg CONTACT_MAIL_TO="${{ secrets.CONTACT_MAIL_TO }}" \
          --build-arg NEXT_PUBLIC_ALGOLIA_APP_ID="${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}" \
          --build-arg NEXT_PUBLIC_ALGOLIA_INDEX_NAME="${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}" \
          --build-arg NEXT_PUBLIC_ALGOLIA_PT_INDEX_NAME="${{ secrets.NEXT_PUBLIC_ALGOLIA_PT_INDEX_NAME }}" \
          --build-arg NEXT_PUBLIC_ALGOLIA_SEARCH_KEY="${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY }}" \
          --build-arg NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT_ID="${{ secrets.NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT_ID }}" \
          --build-arg NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT_ID="${{ secrets.NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT_ID }}" \
          --build-arg NEXT_PUBLIC_GTM_ID="${{ secrets.NEXT_PUBLIC_GTM_ID }}" \
          --build-arg NEXT_PUBLIC_SANITY_API_VERSION="${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}" \
          --build-arg NEXT_PUBLIC_SANITY_DATASET="${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}" \
          --build-arg NEXT_PUBLIC_SANITY_PROJECT_ID="${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}" \
          --build-arg NEXT_PUBLIC_SITE_NAME="${{ secrets.NEXT_PUBLIC_SITE_NAME }}" \
          --build-arg NEXT_PUBLIC_SITE_URL="${{ secrets.NEXT_PUBLIC_SITE_URL }}" \
          --build-arg RESEND_API_KEY="${{ secrets.RESEND_API_KEY }}" \
          --build-arg RESEND_EMAIL_FROM="${{ secrets.RESEND_EMAIL_FROM }}" \
          --build-arg SANITY_API_READ_TOKEN="${{ secrets.SANITY_API_READ_TOKEN }}" \
          --build-arg SANITY_API_TOKEN="${{ secrets.SANITY_API_TOKEN }}" \
          --build-arg SANITY_WEBHOOK_SECRET="${{ secrets.SANITY_WEBHOOK_SECRET }}" \
          -t ${{ secrets.OCIR_REGISTRY }}/${{ secrets.OCI_TENACY_NAMESPACE }}/${{ secrets.OCIR_REPO_NAME }}:preview
      - name: Push Docker Image to Oracle Cloud Registry
        run: docker push ${{ secrets.OCIR_REGISTRY }}/${{ secrets.OCI_TENACY_NAMESPACE }}/${{ secrets.OCIR_REPO_NAME }}:preview
      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     platforms: linux/arm64
      #     context: .
      #     file: Dockerfile
      #     tags: ${{ secrets.OCIR_REGISTRY }}/${{ secrets.OCI_TENACY_NAMESPACE }}/${{ secrets.OCIR_REPO_NAME }}:preview
      #     push: true
      #     build-args: |
      #       ALGOLIA_ADMIN_API_KEY=${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      #       CONTACT_MAIL_TO=${{ secrets.CONTACT_MAIL_TO }}
      #       NEXT_PUBLIC_ALGOLIA_APP_ID=${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
      #       NEXT_PUBLIC_ALGOLIA_INDEX_NAME=${{ secrets.NEXT_PUBLIC_ALGOLIA_INDEX_NAME }}
      #       NEXT_PUBLIC_ALGOLIA_PT_INDEX_NAME=${{ secrets.NEXT_PUBLIC_ALGOLIA_PT_INDEX_NAME }}
      #       NEXT_PUBLIC_ALGOLIA_SEARCH_KEY=${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY }}
      #       NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT_ID }}
      #       NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT_ID }}
      #       NEXT_PUBLIC_GTM_ID=${{ secrets.NEXT_PUBLIC_GTM_ID }}
      #       NEXT_PUBLIC_SANITY_API_VERSION=${{ secrets.NEXT_PUBLIC_SANITY_API_VERSION }}
      #       NEXT_PUBLIC_SANITY_DATASET=${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
      #       NEXT_PUBLIC_SANITY_PROJECT_ID=${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
      #       NEXT_PUBLIC_SITE_NAME=${{ secrets.NEXT_PUBLIC_SITE_NAME }}
      #       NEXT_PUBLIC_SITE_URL=${{ secrets.NEXT_PUBLIC_SITE_URL }}
      #       RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
      #       RESEND_EMAIL_FROM=${{ secrets.RESEND_EMAIL_FROM }}
      #       SANITY_API_READ_TOKEN=${{ secrets.SANITY_API_READ_TOKEN }}
      #       SANITY_API_TOKEN=${{ secrets.SANITY_API_TOKEN }}
      #       SANITY_WEBHOOK_SECRET=${{ secrets.SANITY_WEBHOOK_SECRET }}
